/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AdminListUsersParams {
  limit: number;
  offset: number;
  userId?: number;
  address?: string;
  username?: string;
  email?: string;
  role?: string;
}
/* Response */

export interface AdminListUsersResponse {
  usersTotal: number;
  users: {
    userId: number;
    publicUserId: number;
    username: string;
    address: string;
    lastIp: string;
    lastLoginAt: number;
    loginCount: number;
    role: string;
    email: string;
    updatedAt: number;
    createdAt: number;
  }[];
}
