/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AdminListAlertTypesParams {
  limit: number;
  offset: number;
  alertTypeId?: number;
  name?: string;
  description?: string;
  expression?: string;
}
/* Response */

export interface AdminListAlertTypesResponse {
  alertTypesTotal: number;
  alertTypes: {
    alertTypeId: number;
    name: string;
    description: string;
    expression: string;
  }[];
}
