export const HEDGED_TABLE_COLUMNS = [
  { key: "id", label: "ID", type: "number" },
  { key: "leg1Id", label: "Leg 1 ID", type: "string" },
  { key: "leg2Id", label: "Leg 2 ID", type: "string" },
  { key: "leg1Cloid", label: "Leg 1 CloID", type: "string" },
  { key: "leg2Cloid", label: "Leg 2 CloID", type: "string" },
  { key: "datetime", label: "Datetime", type: "string" },
  { key: "leg1Ins", label: "Leg 1 Instrument", type: "string" },
  { key: "leg2Ins", label: "Leg 2 Instrument", type: "string" },
  { key: "leg1Side", label: "Leg 1 Side", type: "string" },
  { key: "leg2Side", label: "Leg 2 Side", type: "string" },
  { key: "leg1Price", label: "Leg 1 Price", type: "number" },
  { key: "leg2Price", label: "Leg 2 Price", type: "number" },
  { key: "leg1Status", label: "Leg 1 Status", type: "string" },
  { key: "leg2Status", label: "Leg 2 Status", type: "string" },
  { key: "size", label: "Size", type: "number" },
];
