/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AuthorizeParams {
  username: string
  token: string
  service: string
  deviceId: string
  deviceOs: string
}
/* Response */

export interface AuthorizeResponse {
  success: boolean
  userId: number
  role: string
}
