/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LoginParams {
  username: string;
  password: string;
  service: string;
  deviceId: string;
  deviceOs: string;
}
/* Response */

export interface LoginResponse {
  username: string;
  displayName: string;
  avatar?: string;
  role: string;
  userId: number;
  userToken: string;
  adminToken: string;
}
