/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SignupParams {
  username: string
  password: string
  email: string
  phone: string
  agreedTos: boolean
  agreedPrivacy: boolean
}
/* Response */

export interface SignupResponse {
  username: string
  userId: number
}
