/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SubS3TerminalBestAskBestBidParams {
  unsubscribeOtherSymbol?: boolean;
  symbol: string;
}
/* Response */

export interface SubS3TerminalBestAskBestBidResponse {
  data: {
    datetime: number;
    symbol: string;
    price: number;
  }[];
}
/* Response */

export type SubS3TerminalBestAskBestBidStreamResponse =
  SubS3TerminalBestAskBestBidStreamResponse1 &
    SubS3TerminalBestAskBestBidStreamResponse2;
export type SubS3TerminalBestAskBestBidStreamResponse2 = {
  datetime: number;
  symbol: string;
  price: number;
}[];

export type SubS3TerminalBestAskBestBidStreamResponse1 = {};
