/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetSlippage1Params = {};
/* Response */

export interface UserGetSlippage1Response {
  data: {
    id: number;
    eventId: number;
    eventTimestamp: number;
    direction: string;
    symbol: string;
    orderbookBinanceTriggerPrice: number;
    orderbookHyperliquidTriggerPrice: number;
    binanceHyperSpreadBp: number;
    binanceHyperSpreadLevel: string;
    avgBinHyperSpreadBp: number;
    avgBinanceHyperSpreadLevel: string;
    signalBinanceChangeBp: number;
    signalHyperChangeBp: number;
    signalTrendStrengthDx: number;
    actualBuyPrice: number;
    buyPositionUsd: number;
    actualSellPrice: number;
    sellPositionUsd: number;
    fee: number;
    net: number;
    orderbookHyperliquidBidAtSellTime: number;
    orderbookHyperliquidAskAtSellTime: number;
    orderbookBinanceSellPrice: number;
  }[];
}
