/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubEventsParams {
  topic: string;
}
/* Response */

export type UserSubEventsResponse = {};
/* Response */

export interface UserSubEventsStreamResponse {
  topic: string;
  time: string;
  content: string;
}
