/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetStrategyOneAccuracyParams = {};
/* Response */

export interface UserGetStrategyOneAccuracyResponse {
  countCorrect: number;
  countWrong: number;
  accuracy: number;
}
