/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubStrategyOneOrderParams {
  symbol?: string;
}
/* Response */

export interface UserSubStrategyOneOrderResponse {
  data: {
    id: number;
    eventId: number;
    clientId: string;
    exchange: string;
    symbol: string;
    orderType: string;
    side: string;
    price: number;
    volume: number;
    strategyId: number;
    datetime: string;
    effect: string;
    status: string;
  }[];
}
/* Response */

export type UserSubStrategyOneOrderStreamResponse =
  UserSubStrategyOneOrderStreamResponse1 &
    UserSubStrategyOneOrderStreamResponse2;
export type UserSubStrategyOneOrderStreamResponse2 = {
  id: number;
  eventId: number;
  clientId: string;
  exchange: string;
  symbol: string;
  orderType: string;
  side: string;
  price: number;
  volume: number;
  strategyId: number;
  datetime: string;
  effect: string;
  status: string;
}[];

export type UserSubStrategyOneOrderStreamResponse1 = {};
