/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetSignal0Params {
  minLevel?: string;
  timeStart?: string;
  timeEnd?: string;
  symbol?: string;
}
/* Response */

export interface UserGetSignal0Response {
  data: {
    priority: number;
    bp: number;
    id: number;
    datetime: number;
    symbol: string;
    level: string;
  }[];
}
