/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS4EventParams {
  eventId?: number;
}
/* Response */

export interface UserGetS4EventResponse {
  data: {
    id: number;
    timestamp: number;
    leftSymbol: string;
    rightSymbol: string;
    leftCancel: boolean;
    leftQuantity: number;
    leftEventType: string;
    leftAdjustedPrice: number;
    leftPositionDiff: number;
    rightCancel: boolean;
    rightQuantity: number;
    rightEventType: string;
    rightAdjustedPrice: number;
    rightPositionDiff: number;
  }[];
}
