/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetS4ConfigParams = {};
/* Response */

export interface UserGetS4ConfigResponse {
  tradeRight: boolean;
  leftLeg: string;
  leftMargin: boolean;
  leftSide?: string;
  leftQuoteStep: number;
  rightLeg: string;
  rightMargin: boolean;
  rightSide?: string;
  rightQuoteStep: number;
  bidirectional: boolean;
  totalQuantity: number;
  orderQuantity?: string;
  orderQuantityRight?: string;
  orderQuantityLeft?: string;
  maintainPosition?: number;
  maintainPositionRight?: number;
  maintainPositionLeft?: number;
  maxUnhedged?: number;
  openThreshold?: number;
  openThresholdLongRight?: number;
  openThresholdShortRight?: number;
  closeThreshold?: number;
  closeThresholdLongRight?: number;
  closeThresholdShortRight?: number;
  maxOrderNumber: number;
  profitGoal: number;
  leftMakerFee: number;
  leftTakerFee: number;
  rightMakerFee: number;
  rightTakerFee: number;
  takeProfit: boolean;
  stopLoss: boolean;
  hideStatus: boolean;
  orderDelayMs: number;
  preserveOpen: boolean;
  stopFilledSpread: boolean;
  closeOnStop: boolean;
  stopThreshold: number;
  stopCounter: number;
  stopTimePeriodMs: number;
  rightPriceSlippage: number;
}
