/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetFundingRateParams {
  symbol?: string;
}
/* Response */

export interface UserGetFundingRateResponse {
  data: {
    rate: {
      id: number;
      symbol: string;
      exchange: string;
      rate: number;
      tradingVolume: number;
    }[];
    top: {
      id: number;
      symbol: string;
      exchangeLeft: string;
      exchangeRight: string;
      difference: number;
      volumeLeft: number;
      volumeRight: number;
    }[];
  };
}
