/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubStrategy3PositionsOpeningParams {
  unsubscribe?: boolean;
}
/* Response */

export interface UserSubStrategy3PositionsOpeningResponse {
  data: {
    id: number;
    eventId: number;
    cloid: string;
    exchange: string;
    symbol: string;
    status: string;
    price: number;
    size: number;
    filledSize: number;
    cancelOrClose: string;
  }[];
}
/* Response */

export type UserSubStrategy3PositionsOpeningStreamResponse =
  UserSubStrategy3PositionsOpeningStreamResponse1 &
    UserSubStrategy3PositionsOpeningStreamResponse2;
export type UserSubStrategy3PositionsOpeningStreamResponse2 = {
  id: number;
  eventId: number;
  cloid: string;
  exchange: string;
  symbol: string;
  status: string;
  price: number;
  size: number;
  filledSize: number;
  cancelOrClose: string;
}[];

export type UserSubStrategy3PositionsOpeningStreamResponse1 = {};
