/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetS2SlippageParams = {};
/* Response */

export interface UserGetS2SlippageResponse {
  data: {
    id: number;
    triggerEventId: number;
    triggerEventTimestamp: number;
    relativePriceIndicator: string;
    symbol: string;
    binanceTriggerOpenPrice: number;
    hyperTriggerOpenPrice: number;
    slippageBinanceOpenBp: number;
    slippageHyperOpenBp: number;
    triggerOpenCrossSpreadBp: number;
    triggerOpenMeanCrossSpreadBp: number;
    binanceOpenPositionUsd: number;
    binanceActualOpenPrice: number;
    hyperOpenPositionUsd: number;
    hyperActualOpenPrice: number;
    binanceTriggerClosePrice: number;
    hyperTriggerClosePrice: number;
    triggerCloseCrossSpreadBp: number;
    triggerCloseMeanCrossSpreadBp: number;
    binanceClosePositionUsd: number;
    binanceActualClosePrice: number;
    hyperClosePositionUsd: number;
    hyperActualClosePrice: number;
    slippageBinanceCloseBp: number;
    slippageHyperCloseBp: number;
    fee: number;
    binanceBidAskSpreadOpenBp: number;
    hyperBidAskSpreadOpenBp: number;
    binanceBidAskSpreadCloseBp: number;
    hyperBidAskSpreadCloseBp: number;
  }[];
}
