/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS3SignalParams {
  symbol?: string;
}
/* Response */

export interface UserGetS3SignalResponse {
  data: {
    timestamp: number;
    symbol: string;
    rateLeft: number;
    tradingVolumeLeft: number;
    rateRight: number;
    tradingVolumeRight: number;
    rateDifference: number;
    hyperBidBinAskSpreadBp: number;
    meanHyperBidBinAskSpreadBp: number;
    signalLevelLongBinance: string;
    binBidHyperAskSpreadBp: number;
    meanBinBidHyperAskSpreadBp: number;
    signalLevelLongHyper: string;
    hyperBidAskSpreadBp: number;
    binanceBidAskSpreadBp: number;
    binanceBestAskPrice: number;
    hyperliquidBestAskPrice: number;
  }[];
}
