/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSetStrategyStatusParams {
  setStatus?: {
    id: number;
    status: string;
  }[];
}
/* Response */

export interface UserSetStrategyStatusResponse {
  data: {
    id: number;
    status: string;
  }[];
}
