/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubSignal0Params {
  unsubscribeOtherSymbol?: boolean;
  symbol?: string;
}
/* Response */

export interface UserSubSignal0Response {
  data: {
    priority: number;
    bp: number;
    id: number;
    datetime: number;
    symbol: string;
    level: string;
  }[];
}
/* Response */

export type UserSubSignal0StreamResponse = UserSubSignal0StreamResponse1 &
  UserSubSignal0StreamResponse2;
export type UserSubSignal0StreamResponse2 = {
  priority: number;
  bp: number;
  id: number;
  datetime: number;
  symbol: string;
  level: string;
}[];

export type UserSubSignal0StreamResponse1 = {};
