/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS4SignalParams {
  symbol?: string;
}
/* Response */

export interface UserGetS4SignalResponse {
  data: {
    timestamp: number;
    symbol: string;
    hyperBidAskSpreadBp: number;
    binBidHyperAskSpreadBp: number;
    hyperBidBinAskSpreadBp: number;
    binanceMidPrice: number;
    binanceBidPrice: number;
    binanceAskPrice: number;
    hyperBidPrice: number;
    hyperAskPrice: number;
    hyperMidPrice: number;
  }[];
}
