/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS2EventParams {
  eventId?: number;
}
/* Response */

export interface UserGetS2EventResponse {
  data: {
    id: number;
    triggerEventId: number;
    timestamp: number;
    symbol: string;
    eventType: string;
    relativePriceIndicator: string;
    spreadBp: number;
    oppHyperPrice: number;
    oppHyperSize: number;
    oppBinancePrice: number;
    oppBinanceSize: number;
    status: string;
    orders: {
      [k: string]: unknown;
    };
  }[];
}
