/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubFundingRatesParams {
  exchange?: string;
  symbol?: string;
  unsub?: boolean;
}
/* Response */

export interface UserSubFundingRatesResponse {
  data: {
    exchange: string;
    symbol: string;
    rate: number;
    datetime: number;
  }[];
}
/* Response */

export type UserSubFundingRatesStreamResponse =
  UserSubFundingRatesStreamResponse1 & UserSubFundingRatesStreamResponse2;
export type UserSubFundingRatesStreamResponse2 = {
  exchange: string;
  symbol: string;
  rate: number;
  datetime: number;
}[];

export type UserSubFundingRatesStreamResponse1 = {};
