/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetS2PositionParams = {};
/* Response */

export interface UserGetS2PositionResponse {
  data: {
    id: number;
    triggerEventId: number;
    timestamp: number;
    symbol: string;
    relativePriceIndicator: string;
    status: string;
    events: {
      [k: string]: unknown;
    };
  }[];
}
