/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS4JobParams {
  jobId: number;
}
/* Response */

export interface UserGetS4JobResponse {
  id: number;
  isEnabled: boolean;
  leftSymbol: string;
  rightSymbol: string;
  leftExchange: string;
  rightExchange: string;
  accumulatedPositionId: number;
  rightLivePositionId: number;
  leftLivePositionId: number;
  config: {
    tradeRight: boolean;
    leftMargin: boolean;
    leftSide: string;
    leftQuoteStep: number;
    rightMargin: boolean;
    rightSide: string;
    rightQuoteStep: number;
    bidirectional: boolean;
    totalQuantity: number;
    orderQuantity: string;
    orderQuantityRight: string;
    orderQuantityLeft: string;
    maintainPosition: number;
    maintainPositionRight: number;
    maintainPositionLeft: number;
    maxUnhedged: number;
    openThreshold: number;
    openThresholdLongRight: number;
    openThresholdShortRight: number;
    closeThreshold: number;
    closeThresholdLongRight: number;
    closeThresholdShortRight: number;
    maxOrderNumber: number;
    profitGoal: number;
    leftMakerFee: number;
    leftTakerFee: number;
    rightMakerFee: number;
    rightTakerFee: number;
    takeProfit: boolean;
    stopLoss: boolean;
    orderDelayMs: number;
    preserveOpen: boolean;
    stopFilledSpread: boolean;
    closeOnStop: boolean;
    stopThreshold: number;
    stopCounter: number;
    stopTimePeriodMs: number;
    rightPriceSlippage: number;
  };
}
