/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetEvent1Params {
  eventId?: number;
}
/* Response */

export interface UserGetEvent1Response {
  data: {
    id: number;
    timestamp: number;
    symbol: string;
    direction: string;
    opportunityPrice: number;
    opportunitySize: number;
    originalOpportunitySize: number;
    status: string;
    orders: {
      [k: string]: unknown;
    };
  }[];
}
