/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetSignal1Params = {};
/* Response */

export interface UserGetSignal1Response {
  data: {
    timestamp: number;
    symbol: string;
    binanceHyperSpreadBp: number;
    binanceHyperSpreadLevel: string;
    avgBinanceHyperSpreadBp: number;
    avgBinanceHyperSpreadLevel: string;
    hyperBidAskSpreadBp: number;
    binanceChangeBp: number;
    hyperChangeBp: number;
    binanceTrendStrengthDx: number;
    binanceBestAskPrice: number;
    hyperliquidBestAskPrice: number;
  }[];
}
