/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubBestBidAskAcrossExchangesWithPositionEventParams {
  symbol?: string;
}
/* Response */

export interface UserSubBestBidAskAcrossExchangesWithPositionEventResponse {
  data: {
    id: number;
    openingId: number;
    datetime: number;
    expiry: number;
    symbol: string;
    baBn: number;
    bbBn: number;
    baAmountBn: number;
    bbAmountBn: number;
    baHp: number;
    bbHp: number;
    baAmountHp: number;
    bbAmountHp: number;
    hlBalanceCoin: number;
    baBalanceCoin: number;
    opportunitySize: number;
    expired: boolean;
    action: string;
  }[];
}
