/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetS4AccumulatedPositionParams = {};
/* Response */

export interface UserGetS4AccumulatedPositionResponse {
  data: {
    id: number;
    timestamp: number;
    rightSymbol: string;
    leftSymbol: string;
    relativePriceIndicator: string;
    leftExchangeCurrentPrice: number;
    leftExchangeSize: number;
    leftExchangePendingSize: number;
    leftExchangeLastEntryPrice: number;
    leftValue: number;
    rightExchangeCurrentPrice: number;
    rightExchangeSize: number;
    rightExchangePendingSize: number;
    rightExchangeLastEntryPrice: number;
    rightValue: number;
  }[];
}
