/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetS2LivePositionParams = {};
/* Response */

export interface UserGetS2LivePositionResponse {
  data: {
    id: number;
    eventId: number;
    timestamp: number;
    symbol: string;
    relativePriceIndicator: string;
    hyperEntryPrice: number;
    hyperCurrentPrice: number;
    hyperSize: number;
    binanceEntryPrice: number;
    binanceCurrentPrice: number;
    binanceSize: number;
    currentBinanceHyperSpreadBp: number;
    currentProfitEstimate: number;
  }[];
}
