/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubBestBidAskAcrossExchangesParams {
  unsubscribeOtherSymbol?: boolean;
  symbol: string;
}
/* Response */

export interface UserSubBestBidAskAcrossExchangesResponse {
  data: {
    datetime: number;
    binanceAskPrice: number;
    binanceAskVolume: number;
    binanceBidPrice: number;
    binanceBidVolume: number;
    binanceSpotAskPrice: number;
    binanceSpotAskVolume: number;
    binanceSpotBidPrice: number;
    binanceSpotBidVolume: number;
    hyperAskPrice: number;
    hyperAskVolume: number;
    hyperBidPrice: number;
    hyperBidVolume: number;
    bbHa: number;
    baHb: number;
    baHbSpot: number;
    bbHaSpot: number;
  }[];
}
