/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetHedgedOrdersParams {
  strategyId: number;
}
/* Response */

export interface UserGetHedgedOrdersResponse {
  data: {
    id: number;
    leg1Id: string;
    leg2Id: string;
    leg1Cloid: string;
    leg2Cloid: string;
    datetime: string;
    leg1Ins: string;
    leg2Ins: string;
    leg1Side: string;
    leg2Side: string;
    leg1Price: number;
    leg2Price: number;
    leg1Status: string;
    leg2Status: string;
    size: number;
  }[];
}
