/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSetS2ConfigureParams {
  configuration: {
    buyExchange: string;
    sellExchange: string;
    instrument: string;
    orderSize: number;
    maxUnhedged: number;
    targetSpread: number;
    targetPosition: number;
    orderType: string;
  }[];
}
/* Response */

export interface UserSetS2ConfigureResponse {
  success: boolean;
  reason?: string;
}
