/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetOrderParams {
  orderId?: number;
  eventId?: number;
}
/* Response */

export interface UserGetOrderResponse {
  data: {
    id: number;
    strategy: string;
    exchange: string;
    timestamp: number;
    cloid: string;
    triggerEventId: number;
    eventId: number;
    orderType: string;
    status: string;
    symbol: string;
    size: number;
    price: number;
    filledSize: number;
    averageFilledPrice: number;
    fee: number;
  }[];
}
