/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserPlaceOrderMarketParams {
  exchange: string;
  symbol: string;
  side: string;
  price: number;
  size: number;
  localId: string;
}
/* Response */

export interface UserPlaceOrderMarketResponse {
  success: boolean;
  reason: string;
  localId: string;
  clientId: string;
}
