/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS4BestBidAskAcrossExchangesWithPositionEventParams {
  id?: number;
  timeStart?: string;
  timeEnd?: string;
  symbol?: string;
}
/* Response */

export interface UserGetS4BestBidAskAcrossExchangesWithPositionEventResponse {
  data: {
    id: number;
    openingId: number;
    datetime: number;
    expiry: number;
    symbol: string;
    baBn: number;
    bbBn: number;
    baAmountBn: number;
    bbAmountBn: number;
    baBg: number;
    bbBg: number;
    baAmountBg: number;
    bbAmountBg: number;
    bgBalanceCoin: number;
    baBalanceCoin: number;
    opportunitySize: number;
    expired: boolean;
    action: string;
  }[];
}
