/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetLivePosition1Params = {};
/* Response */

export interface UserGetLivePosition1Response {
  data: {
    id: number;
    timestamp: number;
    symbol: string;
    direction: string;
    entryPrice: number;
    size: number;
    entryUsdPrice: number;
    currentHlPrice: number;
    currentBinancePrice: number;
    currentUsdPrice: number;
  }[];
}
