/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserControlStrategyParams {
  strategyId: number;
  config: string;
  paused: boolean;
}
/* Response */

export interface UserControlStrategyResponse {
  success: boolean;
  reason?: string;
}
