/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserSubS2LivePositionParams = {};
/* Response */

export interface UserSubS2LivePositionResponse {
  data: {
    id: number;
    eventId: number;
    timestamp: number;
    symbol: string;
    relativePriceIndicator: string;
    hyperEntryPrice: number;
    hyperCurrentPrice: number;
    hyperSize: number;
    binanceEntryPrice: number;
    binanceCurrentPrice: number;
    binanceSize: number;
    currentBinanceHyperSpreadBp: number;
    currentProfitEstimate: number;
  }[];
}
/* Response */

export type UserSubS2LivePositionStreamResponse =
  UserSubS2LivePositionStreamResponse1 & UserSubS2LivePositionStreamResponse2;
export type UserSubS2LivePositionStreamResponse2 = {
  id: number;
  eventId: number;
  timestamp: number;
  symbol: string;
  relativePriceIndicator: string;
  hyperEntryPrice: number;
  hyperCurrentPrice: number;
  hyperSize: number;
  binanceEntryPrice: number;
  binanceCurrentPrice: number;
  binanceSize: number;
  currentBinanceHyperSpreadBp: number;
  currentProfitEstimate: number;
}[];

export type UserSubS2LivePositionStreamResponse1 = {};
