/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS2LedgerParams {
  eventId?: number;
  symbol?: string;
}
/* Response */

export interface UserGetS2LedgerResponse {
  data: {
    id: number;
    triggerEventId: number;
    datetime: number;
    relativePriceIndicator: string;
    symbol: string;
    binanceOpenOrderId: {
      [k: string]: unknown;
    };
    binanceCloseOrderId: {
      [k: string]: unknown;
    };
    hyperOpenOrderId: {
      [k: string]: unknown;
    };
    hyperCloseOrderId: {
      [k: string]: unknown;
    };
    binanceOpenPositionUsd: number;
    binanceClosePositionUsd: number;
    hyperOpenPositionUsd: number;
    hyperClosePositionUsd: number;
    binanceFee: number;
    hyperFee: number;
    net: number;
  }[];
}
