/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubPositionParams {
  unsubscribe?: boolean;
}
/* Response */

export interface UserSubPositionResponse {
  data: {
    id: number;
    cloid: string;
    exchange: string;
    symbol: string;
    size: number;
    filledSize: number;
    cancelOrClose: string;
  }[];
}
/* Response */

export type UserSubPositionStreamResponse = UserSubPositionStreamResponse1 &
  UserSubPositionStreamResponse2;
export type UserSubPositionStreamResponse2 = {
  id: number;
  cloid: string;
  exchange: string;
  symbol: string;
  size: number;
  filledSize: number;
  cancelOrClose: string;
}[];

export type UserSubPositionStreamResponse1 = {};
