/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetS1LedgerParams {
  eventId?: number;
  symbol?: string;
}
/* Response */

export interface UserGetS1LedgerResponse {
  data: {
    id: number;
    eventId: number;
    datetime: string;
    symbol: string;
    exchange: string;
    direction: string;
    openOrderId: number;
    closeOrderId: number;
    openOrderCloid: string;
    closeOrderCloid: string;
    openPriceUsd: number;
    closePriceUsd: number;
    positionSize: number;
    fee: number;
    closedProfit: number;
  }[];
}
