/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserListTradingSymbolsParams = {};
/* Response */

export interface UserListTradingSymbolsResponse {
  data: {
    exchange: string;
    symbol: string;
    base: string;
    lotSize: number;
    baseDecimals: number;
    quote: string;
    tickSize: number;
    quoteDecimals: number;
  }[];
}
