/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGet5MinSpreadMeanParams = {};
/* Response */

export interface UserGet5MinSpreadMeanResponse {
  data: {
    datetime: number;
    exchange1: string;
    exchange2: string;
    asset: string;
    spreadBuy1: number;
    spreadSell1: number;
  }[];
}
