/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetPerformanceMeasurementParams = {};
/* Response */

export interface UserGetPerformanceMeasurementResponse {
  data: {
    functionName: string;
    durationMs: number;
  }[];
}
/* Response */

export type UserGetPerformanceMeasurementStreamResponse =
  UserGetPerformanceMeasurementStreamResponse1 &
    UserGetPerformanceMeasurementStreamResponse2;
export type UserGetPerformanceMeasurementStreamResponse2 = {
  functionName: string;
  durationMs: number;
}[];

export type UserGetPerformanceMeasurementStreamResponse1 = {};
