/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserListS4JobsParams = {};
/* Response */

export interface UserListS4JobsResponse {
  data: {
    id: number;
    isEnabled: boolean;
    leftSymbol: string;
    rightSymbol: string;
    leftExchange: string;
    rightExchange: string;
    leftAmount: number;
    rightAmount: number;
    accumulatedPositionId: number;
    rightLivePositionId: number;
    leftLivePositionId: number;
  }[];
}
