/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetSignal2Params {
  signal?: string;
  minLevel?: string;
  symbol?: string;
  timeStart?: string;
  timeEnd?: string;
}
/* Response */

export interface UserGetSignal2Response {
  data: {
    baChange: {
      trend?: string;
      exchange?: string;
      priceType?: string;
      before?: number;
      after?: number;
      ratio?: number;
      used?: boolean;
    };
    bbChange: {
      trend?: string;
      exchange?: string;
      priceType?: string;
      before?: number;
      after?: number;
      ratio?: number;
      used?: boolean;
    };
    baHbDiff: {
      binAsk?: number;
      hypBid?: number;
      ratio?: number;
      used?: boolean;
    };
    bbHaDiff: {
      binBid?: number;
      hypAsk?: number;
      ratio?: number;
      used?: boolean;
    };
    id: number;
    datetime: number;
    symbol: string;
    level: string;
  }[];
}
