/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSetSymbolFlag1Params {
  flag: boolean;
  symbol: string;
}
/* Response */

export interface UserSetSymbolFlag1Response {
  success: boolean;
  reason?: string;
}
