/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetPrice0Params {
  timeStart?: string;
  timeEnd?: string;
  symbol: string;
}
/* Response */

export interface UserGetPrice0Response {
  data: {
    datetime: number;
    binancePrice: number;
    binanceSpotPrice: number;
    hyperBidPrice: number;
    hyperOracle: number;
    hyperMark: number;
    differenceInUsd: number;
    differenceInBasisPoints: number;
  }[];
}
