/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSubPrice0Params {
  unsubscribeOtherSymbol?: boolean;
  symbol: string;
}
/* Response */

export interface UserSubPrice0Response {
  data: {
    datetime: number;
    binancePrice: number;
    binanceSpotPrice: number;
    hyperBidPrice: number;
    hyperOracle: number;
    hyperMark: number;
    differenceInUsd: number;
    differenceInBasisPoints: number;
  }[];
}
/* Response */

export type UserSubPrice0StreamResponse = UserSubPrice0StreamResponse1 &
  UserSubPrice0StreamResponse2;
export type UserSubPrice0StreamResponse2 = {
  datetime: number;
  binancePrice: number;
  binanceSpotPrice: number;
  hyperBidPrice: number;
  hyperOracle: number;
  hyperMark: number;
  differenceInUsd: number;
  differenceInBasisPoints: number;
}[];

export type UserSubPrice0StreamResponse1 = {};
