/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetLiveTestCloseOrder1Params = {};
/* Response */

export interface UserGetLiveTestCloseOrder1Response {
  data: {
    symbol: string;
    datetime: number;
    targetPrice: number;
    lastPrice: number;
    trendPrediction: string;
    priceEvent: number;
    priceActualFilled: number;
    priceMarketWhenFilled: number;
    passActualFilled: boolean;
    passMarketWhenFilled: boolean;
    lastOpenPrice: number;
    lastClosePrice: number;
    lastHighPrice: number;
    lastLowPrice: number;
  }[];
}
