/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UserGetS2DebugEventParams = {};
/* Response */

export interface UserGetS2DebugEventResponse {
  data: {
    id: number;
    timestamp: number;
    symbol: string;
    eventType: string;
    relativePriceIndicator: string;
    spreadBp: number;
    oppHyperPrice: number;
    oppHyperSize: number;
    oppBinancePrice: number;
    oppBinanceSize: number;
    status: string;
  }[];
}
