/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetLiveTestAccuracyLogParams {
  tag?: string;
  timeStart?: string;
  timeEnd?: string;
}
/* Response */

export interface UserGetLiveTestAccuracyLogResponse {
  data: {
    datetime: string;
    countPass: number;
    countFail: number;
    accuracy: number;
  }[];
}
