/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetSymbol2Params {
  symbol?: string;
}
/* Response */

export interface UserGetSymbol2Response {
  data: {
    symbol: string;
    status: string;
    flag: boolean;
  }[];
}
